# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'AzitTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  # Pods for NC1

end
